### ISSUE TITLE
request: bump version and publish to registry

### ISSUE THREAD

**Issue by phrohdoh** [carrascomj/bevy_svg_map#9]
Now that we're targeting bevy 0.4, updating the published version on crates.io would be good.

**Comment by carrascomj** [comment]
Hello! I was waiting for [lyon](https://github.com/nical/lyon) to publish the next version so that the version on crates-io does not point to the HEAD of the repository. I'll release 0.1.1 so that people can use it and move it to 0.2.0 when I can point to lyon's crate.


EDIT: it seems like I am required to use the crates-io version, I will see if I can get lyon's maintainer to publish a version pre-17.0.0.

**Comment by carrascomj** [comment]
@phrohdoh Version [0.1.1 is out](https://crates.io/crates/bevy_svg_map)! Feel free to close this issue if it works for you.

**Comment by phrohdoh** [comment]
> @phrohdoh Version [0.1.1 is out](https://crates.io/crates/bevy_svg_map)! Feel free to close this issue if it works for you.

Excellent!  Thank you for your time & efforts.  :-)
